/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SolutionsImport } from './routes/solutions'
import { Route as ResourcesImport } from './routes/resources'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutUsImport } from './routes/about-us'
import { Route as IndexImport } from './routes/index'
import { Route as SolutionsTrainingImport } from './routes/solutions.training'
import { Route as SolutionsTechnologyServicesImport } from './routes/solutions.technology-services'
import { Route as SolutionsRopaSolutionImport } from './routes/solutions.ropa-solution'
import { Route as SolutionsProjectManagementImport } from './routes/solutions.project-management'
import { Route as SolutionsPrivacypalImport } from './routes/solutions.privacypal'
import { Route as SolutionsPrivacyGuideImport } from './routes/solutions.privacy-guide'
import { Route as SolutionsPecbImport } from './routes/solutions.pecb'
import { Route as SolutionsEducationalTechnologyTrainingImport } from './routes/solutions.educational-technology-training'
import { Route as SolutionsDataProtectionImport } from './routes/solutions.data-protection'
import { Route as SolutionsDataBreachResponseImport } from './routes/solutions.data-breach-response'
import { Route as SolutionsCyberSecurityImport } from './routes/solutions.cyber-security'
import { Route as SolutionsCdpoTrainingImport } from './routes/solutions.cdpo-training'
import { Route as SolutionsAIConsultingImport } from './routes/solutions.AI-consulting'
import { Route as ResourcesPrivacyPolicyImport } from './routes/resources.privacy-policy'
import { Route as ResourcesEventsImport } from './routes/resources.events'
import { Route as ResourcesEducationalTechnologyTrainingImport } from './routes/resources.educational-technology-training'
import { Route as ResourcesCookiePolicyImport } from './routes/resources.cookie-policy'
import { Route as ResourcesCdpoTrainingImport } from './routes/resources.cdpo-training'
import { Route as ResourcesBlogImport } from './routes/resources.blog'

// Create/Update Routes

const SolutionsRoute = SolutionsImport.update({
  path: '/solutions',
  getParentRoute: () => rootRoute,
} as any)

const ResourcesRoute = ResourcesImport.update({
  path: '/resources',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutUsRoute = AboutUsImport.update({
  path: '/about-us',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SolutionsTrainingRoute = SolutionsTrainingImport.update({
  path: '/training',
  getParentRoute: () => SolutionsRoute,
} as any)

const SolutionsTechnologyServicesRoute =
  SolutionsTechnologyServicesImport.update({
    path: '/technology-services',
    getParentRoute: () => SolutionsRoute,
  } as any)

const SolutionsRopaSolutionRoute = SolutionsRopaSolutionImport.update({
  path: '/ropa-solution',
  getParentRoute: () => SolutionsRoute,
} as any)

const SolutionsProjectManagementRoute = SolutionsProjectManagementImport.update(
  {
    path: '/project-management',
    getParentRoute: () => SolutionsRoute,
  } as any,
)

const SolutionsPrivacypalRoute = SolutionsPrivacypalImport.update({
  path: '/privacypal',
  getParentRoute: () => SolutionsRoute,
} as any)

const SolutionsPrivacyGuideRoute = SolutionsPrivacyGuideImport.update({
  path: '/privacy-guide',
  getParentRoute: () => SolutionsRoute,
} as any)

const SolutionsPecbRoute = SolutionsPecbImport.update({
  path: '/pecb',
  getParentRoute: () => SolutionsRoute,
} as any)

const SolutionsEducationalTechnologyTrainingRoute =
  SolutionsEducationalTechnologyTrainingImport.update({
    path: '/educational-technology-training',
    getParentRoute: () => SolutionsRoute,
  } as any)

const SolutionsDataProtectionRoute = SolutionsDataProtectionImport.update({
  path: '/data-protection',
  getParentRoute: () => SolutionsRoute,
} as any)

const SolutionsDataBreachResponseRoute =
  SolutionsDataBreachResponseImport.update({
    path: '/data-breach-response',
    getParentRoute: () => SolutionsRoute,
  } as any)

const SolutionsCyberSecurityRoute = SolutionsCyberSecurityImport.update({
  path: '/cyber-security',
  getParentRoute: () => SolutionsRoute,
} as any)

const SolutionsCdpoTrainingRoute = SolutionsCdpoTrainingImport.update({
  path: '/cdpo-training',
  getParentRoute: () => SolutionsRoute,
} as any)

const SolutionsAIConsultingRoute = SolutionsAIConsultingImport.update({
  path: '/AI-consulting',
  getParentRoute: () => SolutionsRoute,
} as any)

const ResourcesPrivacyPolicyRoute = ResourcesPrivacyPolicyImport.update({
  path: '/privacy-policy',
  getParentRoute: () => ResourcesRoute,
} as any)

const ResourcesEventsRoute = ResourcesEventsImport.update({
  path: '/events',
  getParentRoute: () => ResourcesRoute,
} as any)

const ResourcesEducationalTechnologyTrainingRoute =
  ResourcesEducationalTechnologyTrainingImport.update({
    path: '/educational-technology-training',
    getParentRoute: () => ResourcesRoute,
  } as any)

const ResourcesCookiePolicyRoute = ResourcesCookiePolicyImport.update({
  path: '/cookie-policy',
  getParentRoute: () => ResourcesRoute,
} as any)

const ResourcesCdpoTrainingRoute = ResourcesCdpoTrainingImport.update({
  path: '/cdpo-training',
  getParentRoute: () => ResourcesRoute,
} as any)

const ResourcesBlogRoute = ResourcesBlogImport.update({
  path: '/blog',
  getParentRoute: () => ResourcesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesImport
      parentRoute: typeof rootRoute
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsImport
      parentRoute: typeof rootRoute
    }
    '/resources/blog': {
      id: '/resources/blog'
      path: '/blog'
      fullPath: '/resources/blog'
      preLoaderRoute: typeof ResourcesBlogImport
      parentRoute: typeof ResourcesImport
    }
    '/resources/cdpo-training': {
      id: '/resources/cdpo-training'
      path: '/cdpo-training'
      fullPath: '/resources/cdpo-training'
      preLoaderRoute: typeof ResourcesCdpoTrainingImport
      parentRoute: typeof ResourcesImport
    }
    '/resources/cookie-policy': {
      id: '/resources/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/resources/cookie-policy'
      preLoaderRoute: typeof ResourcesCookiePolicyImport
      parentRoute: typeof ResourcesImport
    }
    '/resources/educational-technology-training': {
      id: '/resources/educational-technology-training'
      path: '/educational-technology-training'
      fullPath: '/resources/educational-technology-training'
      preLoaderRoute: typeof ResourcesEducationalTechnologyTrainingImport
      parentRoute: typeof ResourcesImport
    }
    '/resources/events': {
      id: '/resources/events'
      path: '/events'
      fullPath: '/resources/events'
      preLoaderRoute: typeof ResourcesEventsImport
      parentRoute: typeof ResourcesImport
    }
    '/resources/privacy-policy': {
      id: '/resources/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/resources/privacy-policy'
      preLoaderRoute: typeof ResourcesPrivacyPolicyImport
      parentRoute: typeof ResourcesImport
    }
    '/solutions/AI-consulting': {
      id: '/solutions/AI-consulting'
      path: '/AI-consulting'
      fullPath: '/solutions/AI-consulting'
      preLoaderRoute: typeof SolutionsAIConsultingImport
      parentRoute: typeof SolutionsImport
    }
    '/solutions/cdpo-training': {
      id: '/solutions/cdpo-training'
      path: '/cdpo-training'
      fullPath: '/solutions/cdpo-training'
      preLoaderRoute: typeof SolutionsCdpoTrainingImport
      parentRoute: typeof SolutionsImport
    }
    '/solutions/cyber-security': {
      id: '/solutions/cyber-security'
      path: '/cyber-security'
      fullPath: '/solutions/cyber-security'
      preLoaderRoute: typeof SolutionsCyberSecurityImport
      parentRoute: typeof SolutionsImport
    }
    '/solutions/data-breach-response': {
      id: '/solutions/data-breach-response'
      path: '/data-breach-response'
      fullPath: '/solutions/data-breach-response'
      preLoaderRoute: typeof SolutionsDataBreachResponseImport
      parentRoute: typeof SolutionsImport
    }
    '/solutions/data-protection': {
      id: '/solutions/data-protection'
      path: '/data-protection'
      fullPath: '/solutions/data-protection'
      preLoaderRoute: typeof SolutionsDataProtectionImport
      parentRoute: typeof SolutionsImport
    }
    '/solutions/educational-technology-training': {
      id: '/solutions/educational-technology-training'
      path: '/educational-technology-training'
      fullPath: '/solutions/educational-technology-training'
      preLoaderRoute: typeof SolutionsEducationalTechnologyTrainingImport
      parentRoute: typeof SolutionsImport
    }
    '/solutions/pecb': {
      id: '/solutions/pecb'
      path: '/pecb'
      fullPath: '/solutions/pecb'
      preLoaderRoute: typeof SolutionsPecbImport
      parentRoute: typeof SolutionsImport
    }
    '/solutions/privacy-guide': {
      id: '/solutions/privacy-guide'
      path: '/privacy-guide'
      fullPath: '/solutions/privacy-guide'
      preLoaderRoute: typeof SolutionsPrivacyGuideImport
      parentRoute: typeof SolutionsImport
    }
    '/solutions/privacypal': {
      id: '/solutions/privacypal'
      path: '/privacypal'
      fullPath: '/solutions/privacypal'
      preLoaderRoute: typeof SolutionsPrivacypalImport
      parentRoute: typeof SolutionsImport
    }
    '/solutions/project-management': {
      id: '/solutions/project-management'
      path: '/project-management'
      fullPath: '/solutions/project-management'
      preLoaderRoute: typeof SolutionsProjectManagementImport
      parentRoute: typeof SolutionsImport
    }
    '/solutions/ropa-solution': {
      id: '/solutions/ropa-solution'
      path: '/ropa-solution'
      fullPath: '/solutions/ropa-solution'
      preLoaderRoute: typeof SolutionsRopaSolutionImport
      parentRoute: typeof SolutionsImport
    }
    '/solutions/technology-services': {
      id: '/solutions/technology-services'
      path: '/technology-services'
      fullPath: '/solutions/technology-services'
      preLoaderRoute: typeof SolutionsTechnologyServicesImport
      parentRoute: typeof SolutionsImport
    }
    '/solutions/training': {
      id: '/solutions/training'
      path: '/training'
      fullPath: '/solutions/training'
      preLoaderRoute: typeof SolutionsTrainingImport
      parentRoute: typeof SolutionsImport
    }
  }
}

// Create and export the route tree

interface ResourcesRouteChildren {
  ResourcesBlogRoute: typeof ResourcesBlogRoute
  ResourcesCdpoTrainingRoute: typeof ResourcesCdpoTrainingRoute
  ResourcesCookiePolicyRoute: typeof ResourcesCookiePolicyRoute
  ResourcesEducationalTechnologyTrainingRoute: typeof ResourcesEducationalTechnologyTrainingRoute
  ResourcesEventsRoute: typeof ResourcesEventsRoute
  ResourcesPrivacyPolicyRoute: typeof ResourcesPrivacyPolicyRoute
}

const ResourcesRouteChildren: ResourcesRouteChildren = {
  ResourcesBlogRoute: ResourcesBlogRoute,
  ResourcesCdpoTrainingRoute: ResourcesCdpoTrainingRoute,
  ResourcesCookiePolicyRoute: ResourcesCookiePolicyRoute,
  ResourcesEducationalTechnologyTrainingRoute:
    ResourcesEducationalTechnologyTrainingRoute,
  ResourcesEventsRoute: ResourcesEventsRoute,
  ResourcesPrivacyPolicyRoute: ResourcesPrivacyPolicyRoute,
}

const ResourcesRouteWithChildren = ResourcesRoute._addFileChildren(
  ResourcesRouteChildren,
)

interface SolutionsRouteChildren {
  SolutionsAIConsultingRoute: typeof SolutionsAIConsultingRoute
  SolutionsCdpoTrainingRoute: typeof SolutionsCdpoTrainingRoute
  SolutionsCyberSecurityRoute: typeof SolutionsCyberSecurityRoute
  SolutionsDataBreachResponseRoute: typeof SolutionsDataBreachResponseRoute
  SolutionsDataProtectionRoute: typeof SolutionsDataProtectionRoute
  SolutionsEducationalTechnologyTrainingRoute: typeof SolutionsEducationalTechnologyTrainingRoute
  SolutionsPecbRoute: typeof SolutionsPecbRoute
  SolutionsPrivacyGuideRoute: typeof SolutionsPrivacyGuideRoute
  SolutionsPrivacypalRoute: typeof SolutionsPrivacypalRoute
  SolutionsProjectManagementRoute: typeof SolutionsProjectManagementRoute
  SolutionsRopaSolutionRoute: typeof SolutionsRopaSolutionRoute
  SolutionsTechnologyServicesRoute: typeof SolutionsTechnologyServicesRoute
  SolutionsTrainingRoute: typeof SolutionsTrainingRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsAIConsultingRoute: SolutionsAIConsultingRoute,
  SolutionsCdpoTrainingRoute: SolutionsCdpoTrainingRoute,
  SolutionsCyberSecurityRoute: SolutionsCyberSecurityRoute,
  SolutionsDataBreachResponseRoute: SolutionsDataBreachResponseRoute,
  SolutionsDataProtectionRoute: SolutionsDataProtectionRoute,
  SolutionsEducationalTechnologyTrainingRoute:
    SolutionsEducationalTechnologyTrainingRoute,
  SolutionsPecbRoute: SolutionsPecbRoute,
  SolutionsPrivacyGuideRoute: SolutionsPrivacyGuideRoute,
  SolutionsPrivacypalRoute: SolutionsPrivacypalRoute,
  SolutionsProjectManagementRoute: SolutionsProjectManagementRoute,
  SolutionsRopaSolutionRoute: SolutionsRopaSolutionRoute,
  SolutionsTechnologyServicesRoute: SolutionsTechnologyServicesRoute,
  SolutionsTrainingRoute: SolutionsTrainingRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/resources/blog': typeof ResourcesBlogRoute
  '/resources/cdpo-training': typeof ResourcesCdpoTrainingRoute
  '/resources/cookie-policy': typeof ResourcesCookiePolicyRoute
  '/resources/educational-technology-training': typeof ResourcesEducationalTechnologyTrainingRoute
  '/resources/events': typeof ResourcesEventsRoute
  '/resources/privacy-policy': typeof ResourcesPrivacyPolicyRoute
  '/solutions/AI-consulting': typeof SolutionsAIConsultingRoute
  '/solutions/cdpo-training': typeof SolutionsCdpoTrainingRoute
  '/solutions/cyber-security': typeof SolutionsCyberSecurityRoute
  '/solutions/data-breach-response': typeof SolutionsDataBreachResponseRoute
  '/solutions/data-protection': typeof SolutionsDataProtectionRoute
  '/solutions/educational-technology-training': typeof SolutionsEducationalTechnologyTrainingRoute
  '/solutions/pecb': typeof SolutionsPecbRoute
  '/solutions/privacy-guide': typeof SolutionsPrivacyGuideRoute
  '/solutions/privacypal': typeof SolutionsPrivacypalRoute
  '/solutions/project-management': typeof SolutionsProjectManagementRoute
  '/solutions/ropa-solution': typeof SolutionsRopaSolutionRoute
  '/solutions/technology-services': typeof SolutionsTechnologyServicesRoute
  '/solutions/training': typeof SolutionsTrainingRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/resources/blog': typeof ResourcesBlogRoute
  '/resources/cdpo-training': typeof ResourcesCdpoTrainingRoute
  '/resources/cookie-policy': typeof ResourcesCookiePolicyRoute
  '/resources/educational-technology-training': typeof ResourcesEducationalTechnologyTrainingRoute
  '/resources/events': typeof ResourcesEventsRoute
  '/resources/privacy-policy': typeof ResourcesPrivacyPolicyRoute
  '/solutions/AI-consulting': typeof SolutionsAIConsultingRoute
  '/solutions/cdpo-training': typeof SolutionsCdpoTrainingRoute
  '/solutions/cyber-security': typeof SolutionsCyberSecurityRoute
  '/solutions/data-breach-response': typeof SolutionsDataBreachResponseRoute
  '/solutions/data-protection': typeof SolutionsDataProtectionRoute
  '/solutions/educational-technology-training': typeof SolutionsEducationalTechnologyTrainingRoute
  '/solutions/pecb': typeof SolutionsPecbRoute
  '/solutions/privacy-guide': typeof SolutionsPrivacyGuideRoute
  '/solutions/privacypal': typeof SolutionsPrivacypalRoute
  '/solutions/project-management': typeof SolutionsProjectManagementRoute
  '/solutions/ropa-solution': typeof SolutionsRopaSolutionRoute
  '/solutions/technology-services': typeof SolutionsTechnologyServicesRoute
  '/solutions/training': typeof SolutionsTrainingRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/contact': typeof ContactRoute
  '/resources': typeof ResourcesRouteWithChildren
  '/solutions': typeof SolutionsRouteWithChildren
  '/resources/blog': typeof ResourcesBlogRoute
  '/resources/cdpo-training': typeof ResourcesCdpoTrainingRoute
  '/resources/cookie-policy': typeof ResourcesCookiePolicyRoute
  '/resources/educational-technology-training': typeof ResourcesEducationalTechnologyTrainingRoute
  '/resources/events': typeof ResourcesEventsRoute
  '/resources/privacy-policy': typeof ResourcesPrivacyPolicyRoute
  '/solutions/AI-consulting': typeof SolutionsAIConsultingRoute
  '/solutions/cdpo-training': typeof SolutionsCdpoTrainingRoute
  '/solutions/cyber-security': typeof SolutionsCyberSecurityRoute
  '/solutions/data-breach-response': typeof SolutionsDataBreachResponseRoute
  '/solutions/data-protection': typeof SolutionsDataProtectionRoute
  '/solutions/educational-technology-training': typeof SolutionsEducationalTechnologyTrainingRoute
  '/solutions/pecb': typeof SolutionsPecbRoute
  '/solutions/privacy-guide': typeof SolutionsPrivacyGuideRoute
  '/solutions/privacypal': typeof SolutionsPrivacypalRoute
  '/solutions/project-management': typeof SolutionsProjectManagementRoute
  '/solutions/ropa-solution': typeof SolutionsRopaSolutionRoute
  '/solutions/technology-services': typeof SolutionsTechnologyServicesRoute
  '/solutions/training': typeof SolutionsTrainingRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/contact'
    | '/resources'
    | '/solutions'
    | '/resources/blog'
    | '/resources/cdpo-training'
    | '/resources/cookie-policy'
    | '/resources/educational-technology-training'
    | '/resources/events'
    | '/resources/privacy-policy'
    | '/solutions/AI-consulting'
    | '/solutions/cdpo-training'
    | '/solutions/cyber-security'
    | '/solutions/data-breach-response'
    | '/solutions/data-protection'
    | '/solutions/educational-technology-training'
    | '/solutions/pecb'
    | '/solutions/privacy-guide'
    | '/solutions/privacypal'
    | '/solutions/project-management'
    | '/solutions/ropa-solution'
    | '/solutions/technology-services'
    | '/solutions/training'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/contact'
    | '/resources'
    | '/solutions'
    | '/resources/blog'
    | '/resources/cdpo-training'
    | '/resources/cookie-policy'
    | '/resources/educational-technology-training'
    | '/resources/events'
    | '/resources/privacy-policy'
    | '/solutions/AI-consulting'
    | '/solutions/cdpo-training'
    | '/solutions/cyber-security'
    | '/solutions/data-breach-response'
    | '/solutions/data-protection'
    | '/solutions/educational-technology-training'
    | '/solutions/pecb'
    | '/solutions/privacy-guide'
    | '/solutions/privacypal'
    | '/solutions/project-management'
    | '/solutions/ropa-solution'
    | '/solutions/technology-services'
    | '/solutions/training'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/contact'
    | '/resources'
    | '/solutions'
    | '/resources/blog'
    | '/resources/cdpo-training'
    | '/resources/cookie-policy'
    | '/resources/educational-technology-training'
    | '/resources/events'
    | '/resources/privacy-policy'
    | '/solutions/AI-consulting'
    | '/solutions/cdpo-training'
    | '/solutions/cyber-security'
    | '/solutions/data-breach-response'
    | '/solutions/data-protection'
    | '/solutions/educational-technology-training'
    | '/solutions/pecb'
    | '/solutions/privacy-guide'
    | '/solutions/privacypal'
    | '/solutions/project-management'
    | '/solutions/ropa-solution'
    | '/solutions/technology-services'
    | '/solutions/training'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  ContactRoute: typeof ContactRoute
  ResourcesRoute: typeof ResourcesRouteWithChildren
  SolutionsRoute: typeof SolutionsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  ContactRoute: ContactRoute,
  ResourcesRoute: ResourcesRouteWithChildren,
  SolutionsRoute: SolutionsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about-us",
        "/contact",
        "/resources",
        "/solutions"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about-us": {
      "filePath": "about-us.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/resources": {
      "filePath": "resources.tsx",
      "children": [
        "/resources/blog",
        "/resources/cdpo-training",
        "/resources/cookie-policy",
        "/resources/educational-technology-training",
        "/resources/events",
        "/resources/privacy-policy"
      ]
    },
    "/solutions": {
      "filePath": "solutions.tsx",
      "children": [
        "/solutions/AI-consulting",
        "/solutions/cdpo-training",
        "/solutions/cyber-security",
        "/solutions/data-breach-response",
        "/solutions/data-protection",
        "/solutions/educational-technology-training",
        "/solutions/pecb",
        "/solutions/privacy-guide",
        "/solutions/privacypal",
        "/solutions/project-management",
        "/solutions/ropa-solution",
        "/solutions/technology-services",
        "/solutions/training"
      ]
    },
    "/resources/blog": {
      "filePath": "resources.blog.tsx",
      "parent": "/resources"
    },
    "/resources/cdpo-training": {
      "filePath": "resources.cdpo-training.tsx",
      "parent": "/resources"
    },
    "/resources/cookie-policy": {
      "filePath": "resources.cookie-policy.tsx",
      "parent": "/resources"
    },
    "/resources/educational-technology-training": {
      "filePath": "resources.educational-technology-training.tsx",
      "parent": "/resources"
    },
    "/resources/events": {
      "filePath": "resources.events.tsx",
      "parent": "/resources"
    },
    "/resources/privacy-policy": {
      "filePath": "resources.privacy-policy.tsx",
      "parent": "/resources"
    },
    "/solutions/AI-consulting": {
      "filePath": "solutions.AI-consulting.tsx",
      "parent": "/solutions"
    },
    "/solutions/cdpo-training": {
      "filePath": "solutions.cdpo-training.tsx",
      "parent": "/solutions"
    },
    "/solutions/cyber-security": {
      "filePath": "solutions.cyber-security.tsx",
      "parent": "/solutions"
    },
    "/solutions/data-breach-response": {
      "filePath": "solutions.data-breach-response.tsx",
      "parent": "/solutions"
    },
    "/solutions/data-protection": {
      "filePath": "solutions.data-protection.tsx",
      "parent": "/solutions"
    },
    "/solutions/educational-technology-training": {
      "filePath": "solutions.educational-technology-training.tsx",
      "parent": "/solutions"
    },
    "/solutions/pecb": {
      "filePath": "solutions.pecb.tsx",
      "parent": "/solutions"
    },
    "/solutions/privacy-guide": {
      "filePath": "solutions.privacy-guide.tsx",
      "parent": "/solutions"
    },
    "/solutions/privacypal": {
      "filePath": "solutions.privacypal.tsx",
      "parent": "/solutions"
    },
    "/solutions/project-management": {
      "filePath": "solutions.project-management.tsx",
      "parent": "/solutions"
    },
    "/solutions/ropa-solution": {
      "filePath": "solutions.ropa-solution.tsx",
      "parent": "/solutions"
    },
    "/solutions/technology-services": {
      "filePath": "solutions.technology-services.tsx",
      "parent": "/solutions"
    },
    "/solutions/training": {
      "filePath": "solutions.training.tsx",
      "parent": "/solutions"
    }
  }
}
ROUTE_MANIFEST_END */
